global:
  scrape_interval: 10s 
  evaluation_interval: 10s 
scrape_configs:
  - job_name: 'spring-actuator-prometheus'
    metrics_path: '/actuator/prometheus' # Application prometheus endpoint
    static_configs:
      - targets: ['localhost:8080'] # Application host:port
